name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      jdk_version: 8
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK ${{ env.jdk_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.jdk_version }}

      - name: Configure GPG Key
        run: |
          mkdir -p ~/.gnupg/
          echo "$GPG_SIGNING_KEY" > ~/.gnupg/private.key
          gpg --import ~/.gnupg/private.key

      - name: Build
        run: mvn clean install

      - name: Cross-version tests
        run: |
          sudo apt-get update
          sudo apt-get install zsh
          ./run-tests.zsh

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn clean install source:jar javadoc:jar deploy -DskipTests=true --settings settings.xml

      - name: Report coverage
        if: github.ref == 'refs/heads/master'
        run: mvn clean compile jacoco:prepare-agent test jacoco:report coveralls:report -DrepoToken=${{ env.COVERALLS_REPO_TOKEN }}
